### ISSUE TITLE
TadoPlatform v6 - BETA

### ISSUE THREAD

**Issue by SeydX** [SeydX/homebridge-tado-platform#48]
Hello people,

as some of you may know, I am currently working on version 6 of the Tado plugin. Here in the thread I will inform all interested about the progress. Version 6 will have a lot of new stuff, config ui x support and even a custom UI. I have picked out many ideas from you here and made a note of them.

If you still have wishes or suggestions for improvement, you can share them here

## Beta

All who would like to participate in the beta are welcome. To install the beta version, simply do the following:

```sudo npm i -g homebridge-tado-platform@beta```

And on the following page you can find details about the new config and its description

https://github.com/SeydX/homebridge-tado-platform/tree/beta

If you encounter any bugs during the testing phase, please report them here. Please remember to enable debug in config.json (``"debug": true``).

To fix the errors as soon as possible, please include the log and config.json

## First Look (Custom UI) 
__2021-03-06__
![hb_tadoplatform_ui_test](https://user-images.githubusercontent.com/34152761/110205296-860ae100-7e77-11eb-9f77-9eb38dccfb46.gif)

## TODO
- [x] Config UI X support (config.schema.json)
- [x] Custom UI
- [x] Support for non config ui x user
- [x] Auto-fill config for non config ui x user
- [x] HB 1.3 support
  - Support new onGet/onSet event
- [x] Refactored code
- [x] Multiple tado accounts
  - Possibility to control multiple homes
- [x] Customizable temperature unit via HomeKit
- [x] Customizable Modes (AUTO | HEAT | COOL | OFF) or (ON | OFF)
- [x] Deactivatable battery indicator (support for old gen thermostats)
- [x] Customizable zone termination, separate for each zone
- [x] Delay Switch
  - [x] Delay as switch characteristic with adjustable timer characteristic for automations
  - [x] Auto turn off options
- [x] Separate humidity sensor
- [x] Separate temperature sensor
- [x] Boiler with adjustable accessory type
  - [x] Switch (if no temperature is supported) 
  - [x] Faucet (if no temperature supported)
  - [x] HeaterCooler (if temperature supported)
- [x] Grouped Central Switch with custom characteristics 
  - [x] Overall heat in h for day/month/year
  - [x] Thermostat/Boiler states (manual, auto, off)
  - [x] Boost trigger switch
  - [x] Resume shedule trigger switch
  - [x] Turn off trigger switch
- [x] OpenWindow
  - [x] Grouped Switch: Enables open window and trigger open window detection
  - [x] Contact: Read-only open window state as contact sensor
- [x] Presence Lock
  - [x] As Security System
  - [x] As Grouped Switch Accessory 
- [x] Air Quality
  - [x] Weather
  - [x] Zones
- [x] FakeGato
  - [x] Thermostats
  - [x] HeaterCooler
  - [x] Temperature sensors
  - [x] Humidity sensors
  - [x] Contact sensors (window)
- [x] Telegram
  - [x] Presence
  - [x] OpenWindow
- [x] Child Lock Switches as Grouped Switch Accessory
- [x] Better error handling

Thanks to all for the support, suggestion, ideas etc.

Seyd

**Comment by det-box** [comment]
A wish, after opening and closing again, timer for delayed switching on of the heating. In the event that you go in and out of the patio door several times. That the heating doesn't always go on and off.

**Comment by SeydX** [comment]
@det-box 

Wouldn't it be better to have a simpler solution for this that is easily accessible to all? With config.json you could solve this with a "delay" option, so a thermostat would only switch if the "new" state is different, even after X seconds.

**Comment by det-box** [comment]
Yes, it would work that way.

**Comment by det-box** [comment]
Correction: 
Just to clarify again. 
... so that a thermostat only switches on if the window detection is no different when the window is closed, even after X seconds.

**Comment by SeydX** [comment]
@det-box 

Yesi understood you.

 But we don't have to limit that to windows. We can use the "logic" generally on EVERYTHING.

If e.g. delay = 10s and thermostat is switched to OFF by an automation (e.g. because of window open), then the plugin should check if the thermostat is also OFF AFTER 10 seconds. If yes, then the thermostat is also switched.

**Comment by det-box** [comment]
Sorry,
That's not what I mean, if the window is closed, wait 2 minutes before the thermostat turns on. If the window is opened again, the timer is reset and the 2min starts again.

**Comment by beatpaul** [comment]
Thx for your great plugin!
Im really looking forward testing the new version!
When will it be released?

**Comment by SeydX** [comment]
@beatpaul 

I think later this week I will publish it

**Comment by SeydX** [comment]
@beatpaul 

The beta version has been released. Check the issue =)

**Comment by beatpaul** [comment]
Hi!
Im tested it, by deleting my old config, installing the Plugin, but i get this errorlog:

```
[3/11/2021, 8:48:19 AM] [TadoPlatform] TypeError: Cannot read property 'includes' of undefined
    at /usr/local/lib/node_modules/homebridge-tado-platform/src/helper/deviceHandler.js:537:137
    at Array.filter (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-tado-platform/src/helper/deviceHandler.js:537:62
    at Array.forEach (<anonymous>)
    at updateZones (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/deviceHandler.js:534:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at getStates (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/deviceHandler.js:415:9)
```

It seems it doesn't include my Tado device (i have Tado v1 and an external sensor that i dont use)

in my former config i hade to activate the device

thx for your help

Paul

**Comment by SeydX** [comment]
@beatpaul 

it seems the problem occurs while the plugin looks for a batteryState but your v1 doesnt support it?

**Comment by SeydX** [comment]
@beatpaul 

v6.0.0-beta.1 is online

**Comment by beatpaul** [comment]
H!

in the beginning i still had an error message: 
```
[3/11/2021, 12:02:12 PM] [TadoPlatform] TypeError: Cannot read property 'includes' of undefined
    at /usr/local/lib/node_modules/homebridge-tado-platform/src/helper/deviceHandler.js:540:86
    at Array.filter (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-tado-platform/src/helper/deviceHandler.js:540:38
    at Array.forEach (<anonymous>)
    at updateZones (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/deviceHandler.js:535:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at getStates (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/deviceHandler.js:416:9)
```
but after activating "no Battery"  it works great now !

thx

**Comment by SeydX** [comment]
@beatpaul 

ah, the error will be fixed in the next beta version, thx! =)

**Comment by SeydX** [comment]
@beatpaul 

should be fixed in beta v4

There was several improvements in Beta v4:

- Open Window "switches" are grouped now as default
- Child Locks are grouped now as default
- Central Switch/Boost Switch/Shedule Switch/Turn Off Switch are grouped now as default
- New option to change Presence Lock accessory type (SWITCH/ALARM)
- Switching central switch, boost switch, shedule switch and turn off switch will now switch the accessories in HomeKit immediately
- Added compareVersion to check config ui x version

If you use Open Window switches, Child Lock Switches, Central/Boost/Shedule/TurnOff Switches or Precene Lock, please turn them off after updating to Beta v4. After restarting Homebridge, you can turn them on again

**Comment by Nastras** [comment]
If you have time, please take a look at the forum. Thank you!

**Comment by SeydX** [comment]
@Nastras 

v6.0.0-beta.9 released

**Comment by Somberland** [comment]
v6.0.0-beta.10 works great for me 👍 
one question about the `Mode: Timer`:

In the TadoApp I can set up the timer-mode after "manual" changing the temperature. Am I correct in assuming that the timer mode replicates this functionality internally? So I can use the settings form TadoApp (and config as `manual`) or use the timer-setting in the plugin-config? Are there any advantages/disadvantages depending on which variant I'll  use?


![IMG_FA5E8362F670-1](https://user-images.githubusercontent.com/5808345/111025922-a5f65380-83e7-11eb-870b-9e4f173869e4.jpeg)

**Comment by SeydX** [comment]
Hey guys,

v6.0.0-beta.15 is online with some major changes in the background. Therefore, if u use "Central Switch", please disable it after restart so it should be removed from HomeKit. Afterwars, you can enable it again

@Somberland 

The plugin can handle severeal modes. 

- MANUAL: Changes the mode UNTIL the user changes it manually (without any timer)
- TIMER: Changes the mode only for the given time (in minutes)
- AUTO: The values are taken over directly in AUTO mode in tado app

**Comment by SeydX** [comment]
Hey guys,

thx all for testing the beta version. It is officially released now. Have fun with version 6!

**Comment by Nastras** [comment]
If you have time, please take a look at the forum again. Thank you!
